// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9g1e5LLLDS4TGJiaFCSEyH
// Component: POnAEYK1Z5mh

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import ActivationProcess from "../../ActivationProcess"; // plasmic-import: 1sYr9T24RxmQ/component
import ActivationOfficeCost from "../../ActivationOfficeCost"; // plasmic-import: Uq71V-zgrZxq/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_fragment_design_system_css from "../fragment_design_system/plasmic.module.css"; // plasmic-import: h9Dbk9ygddw7UVEq1NNhKi/projectcss
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 9g1e5LLLDS4TGJiaFCSEyH/projectcss
import sty from "./PlasmicActivationOfficeCost3.module.css"; // plasmic-import: POnAEYK1Z5mh/css

createPlasmicElementProxy;

export type PlasmicActivationOfficeCost3__VariantMembers = {};
export type PlasmicActivationOfficeCost3__VariantsArgs = {};
type VariantPropType = keyof PlasmicActivationOfficeCost3__VariantsArgs;
export const PlasmicActivationOfficeCost3__VariantProps =
  new Array<VariantPropType>();

export type PlasmicActivationOfficeCost3__ArgsType = {};
type ArgPropType = keyof PlasmicActivationOfficeCost3__ArgsType;
export const PlasmicActivationOfficeCost3__ArgProps = new Array<ArgPropType>();

export type PlasmicActivationOfficeCost3__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<"div">;
  text?: Flex__<"div">;
  activationProcess?: Flex__<typeof ActivationProcess>;
  activationOfficeCost?: Flex__<typeof ActivationOfficeCost>;
};

export interface DefaultActivationOfficeCost3Props {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicActivationOfficeCost3__RenderFunc(props: {
  variants: PlasmicActivationOfficeCost3__VariantsArgs;
  args: PlasmicActivationOfficeCost3__ArgsType;
  overrides: PlasmicActivationOfficeCost3__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">
          {PlasmicActivationOfficeCost3.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicActivationOfficeCost3.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicActivationOfficeCost3.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_fragment_design_system_css.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames(projectcss.all, sty.header)}
          >
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text
              )}
            >
              {"\u0628\u06cc\u0639\u0627\u0646\u0647"}
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__wLaJb)}>
            <div className={classNames(projectcss.all, sty.freeBox__btaRg)}>
              <ActivationProcess
                data-plasmic-name={"activationProcess"}
                data-plasmic-override={overrides.activationProcess}
                className={classNames("__wab_instance", sty.activationProcess)}
                step={3}
              />
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___2TZEj)}>
              <ActivationOfficeCost
                data-plasmic-name={"activationOfficeCost"}
                data-plasmic-override={overrides.activationOfficeCost}
                className={classNames(
                  "__wab_instance",
                  sty.activationOfficeCost
                )}
                hasOnlineVisit={(() => {
                  try {
                    return $ctx.query.onlineVisit == "true";
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return false;
                    }
                    throw e;
                  }
                })()}
                userId={(() => {
                  try {
                    return $ctx.query.user_id;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
              />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "text", "activationProcess", "activationOfficeCost"],
  header: ["header", "text"],
  text: ["text"],
  activationProcess: ["activationProcess"],
  activationOfficeCost: ["activationOfficeCost"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: "div";
  text: "div";
  activationProcess: typeof ActivationProcess;
  activationOfficeCost: typeof ActivationOfficeCost;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicActivationOfficeCost3__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicActivationOfficeCost3__VariantsArgs;
    args?: PlasmicActivationOfficeCost3__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicActivationOfficeCost3__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicActivationOfficeCost3__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicActivationOfficeCost3__ArgProps,
          internalVariantPropNames: PlasmicActivationOfficeCost3__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicActivationOfficeCost3__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicActivationOfficeCost3";
  } else {
    func.displayName = `PlasmicActivationOfficeCost3.${nodeName}`;
  }
  return func;
}

export const PlasmicActivationOfficeCost3 = Object.assign(
  // Top-level PlasmicActivationOfficeCost3 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    text: makeNodeComponent("text"),
    activationProcess: makeNodeComponent("activationProcess"),
    activationOfficeCost: makeNodeComponent("activationOfficeCost"),

    // Metadata about props expected for PlasmicActivationOfficeCost3
    internalVariantProps: PlasmicActivationOfficeCost3__VariantProps,
    internalArgProps: PlasmicActivationOfficeCost3__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "مبلغ بیعانه",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicActivationOfficeCost3;
/* prettier-ignore-end */
